import { mutation } from "../_generated/server";
import { Id } from "../_generated/dataModel";

type TestProfile = {
  fullName: string;
  dateOfBirth: string;
  gender: "male" | "female" | "other";
  ukCity: string;
  ukPostcode: string;
  religion: string;
  caste: string;
  motherTongue: string;
  height: string;
  maritalStatus?: "single" | "divorced" | "widowed" | "annulled";
  education: string;
  occupation: string;
  annualIncome: number;
  aboutMe: string;
  partnerPreferenceAgeMin: number;
  partnerPreferenceAgeMax: number;
  partnerPreferenceReligion: string[];
  partnerPreferenceUkCity: string[];
  profileImageIds: Id<"_storage">[];
  phoneNumber: string;
  diet: "vegetarian" | "non-vegetarian" | "vegan" | "eggetarian" | "other";
  smoking: "no" | "occasionally" | "yes";
  drinking: "no" | "occasionally" | "yes";
  physicalStatus: "normal" | "differently-abled" | "other";
};

export default mutation({
  args: {},
  handler: async (ctx, args) => {
    const testProfiles: TestProfile[] = [
      {
        fullName: "Aisha Khan",
        dateOfBirth: "1995-05-20",
        gender: "female",
        ukCity: "London",
        ukPostcode: "E1 6AN",
        religion: "Islam",
        caste: "Sunni",
        motherTongue: "Urdu",
        height: "5ft 4in",
        maritalStatus: "single",
        education: "BSc Psychology",
        occupation: "Teacher",
        annualIncome: 32000,
        aboutMe: "I love reading, traveling, and spending time with family.",
        partnerPreferenceAgeMin: 27,
        partnerPreferenceAgeMax: 35,
        partnerPreferenceReligion: ["Islam"],
        partnerPreferenceUkCity: ["London", "Manchester"],
        profileImageIds: [],
        phoneNumber: "+44 7123 456789",
        diet: "vegetarian",
        smoking: "no",
        drinking: "no",
        physicalStatus: "normal",
      },
      {
        fullName: "Omar Ali",
        dateOfBirth: "1992-11-15",
        gender: "male",
        ukCity: "Manchester",
        ukPostcode: "M1 2AB",
        religion: "Islam",
        caste: "Sunni",
        motherTongue: "Arabic",
        height: "5ft 10in",
        maritalStatus: "single",
        education: "MSc Computer Science",
        occupation: "Software Engineer",
        annualIncome: 48000,
        aboutMe: "Software engineer, foodie, and football fan.",
        partnerPreferenceAgeMin: 25,
        partnerPreferenceAgeMax: 32,
        partnerPreferenceReligion: ["Islam"],
        partnerPreferenceUkCity: ["Manchester", "London"],
        profileImageIds: [],
        phoneNumber: "+44 7123 456790",
        diet: "non-vegetarian",
        smoking: "no",
        drinking: "occasionally",
        physicalStatus: "normal",
      },
      {
        fullName: "Sara Patel",
        dateOfBirth: "1996-03-10",
        gender: "female",
        ukCity: "Birmingham",
        ukPostcode: "B1 1AA",
        religion: "Hinduism",
        caste: "Patel",
        motherTongue: "Gujarati",
        height: "5ft 6in",
        maritalStatus: "single",
        education: "BA English",
        occupation: "Writer",
        annualIncome: 29000,
        aboutMe: "Yoga enthusiast and aspiring chef.",
        partnerPreferenceAgeMin: 27,
        partnerPreferenceAgeMax: 34,
        partnerPreferenceReligion: ["Hinduism"],
        partnerPreferenceUkCity: ["Birmingham"],
        profileImageIds: [],
        phoneNumber: "+44 7123 456791",
        diet: "vegetarian",
        smoking: "no",
        drinking: "no",
        physicalStatus: "normal",
      },
      {
        fullName: "James Smith",
        dateOfBirth: "1990-07-22",
        gender: "male",
        ukCity: "Leeds",
        ukPostcode: "LS1 1UR",
        religion: "Christianity",
        caste: "",
        motherTongue: "English",
        height: "6ft 0in",
        maritalStatus: "divorced",
        education: "BEng Civil Engineering",
        occupation: "Engineer",
        annualIncome: 41000,
        aboutMe: "Enjoys hiking and photography.",
        partnerPreferenceAgeMin: 30,
        partnerPreferenceAgeMax: 40,
        partnerPreferenceReligion: ["Christianity", "No Religion"],
        partnerPreferenceUkCity: ["Leeds", "Manchester"],
        profileImageIds: [],
        phoneNumber: "+44 7123 456792",
        diet: "non-vegetarian",
        smoking: "occasionally",
        drinking: "yes",
        physicalStatus: "normal",
      },
      {
        fullName: "Fatima Begum",
        dateOfBirth: "1994-12-05",
        gender: "female",
        ukCity: "London",
        ukPostcode: "E2 8AA",
        religion: "Islam",
        caste: "Shia",
        motherTongue: "Bengali",
        height: "5ft 2in",
        maritalStatus: "single",
        education: "BA Fine Arts",
        occupation: "Designer",
        annualIncome: 35000,
        aboutMe: "Passionate about art and design.",
        partnerPreferenceAgeMin: 28,
        partnerPreferenceAgeMax: 36,
        partnerPreferenceReligion: ["Islam"],
        partnerPreferenceUkCity: ["London"],
        profileImageIds: [],
        phoneNumber: "+44 7123 456793",
        diet: "vegan",
        smoking: "no",
        drinking: "no",
        physicalStatus: "normal",
      },
      {
        fullName: "Priya Singh",
        dateOfBirth: "1993-09-18",
        gender: "female",
        ukCity: "Glasgow",
        ukPostcode: "G1 1AA",
        religion: "Sikhism",
        caste: "Khatri",
        motherTongue: "Punjabi",
        height: "5ft 5in",
        maritalStatus: "single",
        education: "MSc Biology",
        occupation: "Researcher",
        annualIncome: 37000,
        aboutMe: "Loves music and volunteering.",
        partnerPreferenceAgeMin: 27,
        partnerPreferenceAgeMax: 34,
        partnerPreferenceReligion: ["Sikhism"],
        partnerPreferenceUkCity: ["Glasgow", "Edinburgh"],
        profileImageIds: [],
        phoneNumber: "+44 7123 456794",
        diet: "vegetarian",
        smoking: "no",
        drinking: "no",
        physicalStatus: "normal",
      },
      {
        fullName: "David Brown",
        dateOfBirth: "1989-02-14",
        gender: "male",
        ukCity: "Manchester",
        ukPostcode: "M2 3AE",
        religion: "No Religion",
        caste: "",
        motherTongue: "English",
        height: "5ft 11in",
        education: "BA History",
        occupation: "Librarian",
        annualIncome: 28000,
        aboutMe: "Runner, reader, and coffee lover.",
        partnerPreferenceAgeMin: 30,
        partnerPreferenceAgeMax: 38,
        partnerPreferenceReligion: ["No Religion", "Christianity"],
        partnerPreferenceUkCity: ["Manchester", "Liverpool"],
        profileImageIds: [],
        phoneNumber: "+44 7123 456795",
        diet: "eggetarian",
        smoking: "no",
        drinking: "occasionally",
        physicalStatus: "normal",
      },
      {
        fullName: "Layla Hussain",
        dateOfBirth: "1997-06-30",
        gender: "female",
        ukCity: "Birmingham",
        ukPostcode: "B2 4QA",
        religion: "Islam",
        caste: "Sunni",
        motherTongue: "Arabic",
        height: "5ft 3in",
        maritalStatus: "single",
        education: "BSc Mathematics",
        occupation: "Accountant",
        annualIncome: 34000,
        aboutMe: "Baker and aspiring novelist.",
        partnerPreferenceAgeMin: 26,
        partnerPreferenceAgeMax: 33,
        partnerPreferenceReligion: ["Islam"],
        partnerPreferenceUkCity: ["Birmingham", "London"],
        profileImageIds: [],
        phoneNumber: "+44 7123 456796",
        diet: "vegetarian",
        smoking: "no",
        drinking: "no",
        physicalStatus: "normal",
      },
      {
        fullName: "Mohammed Yusuf",
        dateOfBirth: "1991-04-12",
        gender: "male",
        ukCity: "Leeds",
        ukPostcode: "LS2 3AA",
        religion: "Islam",
        caste: "Sunni",
        motherTongue: "Urdu",
        height: "5ft 9in",
        maritalStatus: "single",
        education: "BSc Physics",
        occupation: "Technician",
        annualIncome: 31000,
        aboutMe: "Cricket fan and tech enthusiast.",
        partnerPreferenceAgeMin: 28,
        partnerPreferenceAgeMax: 36,
        partnerPreferenceReligion: ["Islam"],
        partnerPreferenceUkCity: ["Leeds", "Bradford"],
        profileImageIds: [],
        phoneNumber: "+44 7123 456797",
        diet: "non-vegetarian",
        smoking: "no",
        drinking: "no",
        physicalStatus: "normal",
      },
      {
        fullName: "Emily Clark",
        dateOfBirth: "1995-08-25",
        gender: "female",
        ukCity: "London",
        ukPostcode: "N1 9GU",
        religion: "Christianity",
        caste: "",
        motherTongue: "English",
        height: "5ft 7in",
        maritalStatus: "single",
        education: "BA Fine Arts",
        occupation: "Artist",
        annualIncome: 33000,
        aboutMe: "Enjoys painting and city walks.",
        partnerPreferenceAgeMin: 27,
        partnerPreferenceAgeMax: 35,
        partnerPreferenceReligion: ["Christianity"],
        partnerPreferenceUkCity: ["London", "Cambridge"],
        profileImageIds: [],
        phoneNumber: "+44 7123 456798",
        diet: "vegan",
        smoking: "no",
        drinking: "occasionally",
        physicalStatus: "normal",
      },
    ];

    for (let i = 0; i < testProfiles.length; i++) {
      const userId = await ctx.db.insert("users", {
        clerkId: `test_user_${i + 1}`,
        email: `test${i + 1}@aroosi.dev`,
      });
      const profile = { ...testProfiles[i] };
      // Fix caste to always be a string
      if (typeof profile.caste !== "string") {
        profile.caste = "";
      }
      await ctx.db.insert("profiles", {
        userId,
        clerkId: `test_user_${i + 1}`,
        isProfileComplete: true,
        ...profile,
        gender: profile.gender as "male" | "female" | "other",
        profileImageIds: profile.profileImageIds || [],
        createdAt: Date.now(),
      });
    }
    return "Seeded 10 test profiles!";
  },
});
