name: Dependency Review

on:
  pull_request:
    branches: [ "**" ]

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Dependency Review
        uses: actions/dependency-review-action@v4
        with:
          fail-on-severity: high
          allow-licenses: |-
            MIT
            ISC
            Apache-2.0
            BSD-2-Clause
            BSD-3-Clause
          deny-licenses: GPL-1.0,GPL-2.0,GPL-3.0,AGPL-3.0,LGPL-3.0


