name: Secret Scan (TruffleHog)

on:
  pull_request:
    branches: [ "**" ]
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  trufflehog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run TruffleHog against diff
        uses: trufflesecurity/trufflehog@v3.80.6
        with:
          scan: git
          path: .
          fail: true
          extra_args: --only-verified


